apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:oXjvmbys6BjvGdjjkP2mz2n6UeifxoJ67RWWOshZp8MYRjow59ye5Zhnytp7xKrRVRmN+xUeyeecR2HjLT8t7BV43d62MExkaBndFPaEquEyl+tLaY/DfCpxnUZBdvGopawSzcz7UIScn4QK9AyCXE037zISvXVPiHudBuruoRcYIKyHyX4dN+DO02JNIjkbQzzb/2POV+LRO3GWlolefYRaPjUfkDOe3g56Ys33No/YJqzvFTipX5e6JEM+fSXo7NJ0EPVsORGHPe3DRD5j4FZsfSI4F9UJ2r6KJnt5G91ccwwvtRxKYFSGHOo=,iv:26b9ADHJ4/Guk8KyjC3QngOo2LenotSkrYKfnxi9Dag=,tag:ZWm35kPNGduqHSn4+8JFgA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aef04c6mk3x4tqypazlghlhzhyxqmq2kgs38g3u9tfc6292tspysq0x74t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVk1XWFZkdC9yTHRGcUNq
            MjhickVpNTViamwrTmNMZVlVbG50Z3ZOelQwCmlJeC92SGt3SWR4U3lrc3lSd1Zi
            ejFmRHgyT3N3UU04WWlzRThic1h0N0kKLS0tIDl4czRLUHFkMllocG5jaE1YVWh4
            V2VQcDU2dUMyRi91cC9IZUFkVVpHOUUKBDrXoxuACxlUINjhJpdAm+pYHff7Vi7D
            UCmdKP1OXm7eU7JC/V3fofv0YCjifCqRv3vYBTL3iUPup+APPz3bOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T20:56:17Z"
    mac: ENC[AES256_GCM,data:Xn9UhXoxxEjwQw/SLeQgiPTaZwsLtCEE5oGQqJv0t1X7a4aUM4HZoeWnxr6Wo4Vls+TPgWTEDatYeZEh5IYn07ucBs1XhwRCi3GH5PzErxW/qVHFpk2VY2t3kwLUoxhyqB5QBuXASDFJllxRzMO9SxnHDuwA5x74L36tvjL9ps8=,iv:+aeYBVdsrhnJdsnCq0P9KbzIQtAvbaY7WsSpPDrU1mQ=,tag:liBfctisJSp22wQmYIpFCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
