apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:kzC+39d+abU=,iv:eRNMDzvepjpnnPoOjbntsvwn15D5bQgGwNHxJ13wvSA=,tag:HfVqQpTUk9gMZeyarWVkMQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:euk8gLkxGmZqeWCava+cdGJMEZw=,iv:hb+tWDNOkbMQvtyPPlx1MjuFyITWgO4Q8BxSup3ylyE=,tag:Pz/qfmzU1B48JFDDpB23ng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aef04c6mk3x4tqypazlghlhzhyxqmq2kgs38g3u9tfc6292tspysq0x74t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ0JYTTN4akF1ZWZFR2Jz
            YnV1NXF0Q1drM2xvUzhUNm53M1FZcldPWkU4ClI4N1M4V0I3S29nZWdzNHlrd0ta
            V3ZGd2pvbXBjMnN5MmVPNjIwQ1p0UlkKLS0tIHVRckJYQnc2d2xzMmpuaWZGVFpM
            TTJPZnI4b1ZtaGttTUUwSG11Y0hjZU0KHYksC56srYdvii4roAGqDcJJj4WxD1oA
            V7Q9ngl4vpm2GKBpXNaZFdXwtwIVjL9TXOe7oljFiZ0f0gXrKVKBlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T17:24:18Z"
    mac: ENC[AES256_GCM,data:xWjk1ZPnN5KQi+ZAgOy5JZL3uWyyCMXUvKqENhDLGEGN4nCVsVKp5uPYcS/6vMLN6GiHA0jlfv9GaM/5KCII9iiXk+G/rWJDeX6np0jM4XbolJZtrmmLpHc66C9zxomD4WRezqD7wXts8bMxxQe6vCKcVFcfA3uU2eM074ItZUw=,iv:uxxQ0ExDBApkzAU8kbIL/uZ19mJhCGXSVu3uS99J1Qk=,tag:TLuwC17HumrrDVR2DK7d2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
