apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-pvc
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec: 
      containers:
        - name: vikunja
          image: vikunja/vikunja
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "http://vikunja.kptasznik.net"
            - name: VIKUNJA_DATABASE_HOST
              value: postgres.vikunja.svc.cluster.local
            - name: VIKUNJA_DATABASE_PASSWORD
              value: changeme
            - name: VIKUNJA_DATABASE_TYPE
              value: postgres
            - name: VIKUNJA_DATABASE_USER
              value: vikunja
            - name: VIKUNJA_DATABASE_DATABASE
              value: vikunja
            - name: VIKUNJA_SERVICE_JWTSECRET
              value: "your-super-secure-secret"
          volumeMounts:
            - name: vikunja-files
              mountPath: /app/vikunja/files
      volumes:
        - name: vikunja-files
          persistentVolumeClaim:
            claimName: vikunja-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja 
spec:
  ports:
    - port: 3456
      targetPort: 3456
  selector:
    app: vikunja

