apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wger 
  namespace: wger
spec:
  interval: 30m
  chart:
    spec:
      chart: "wger"
      version: "0.2.4"


      sourceRef:
        kind: HelmRepository
        name: wger 
        namespace: wger
      interval: 12h
  values:
    ingress:
      enabled: true
      ingressClassName: traefik  # lub inna, np. traefik, jeśli używasz innego kontrolera
      url:
      - wger.kptasznik.net
          # <- ustaw domenę, którą obsłuży Ingress
              #tls:
       # - hosts:
          #  - wger.local
         # secretName: wger-tls
